### ISSUE TITLE
Behat: failing with Firefox 56-57

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2264]
### Current behavior

When launching behat locally with Firefox 57, I get the following error (cut down because it's very long):
```
  Scenario: See the company reports link on the admin page # features/accessCompanyReports.feature:7
    Given I am a platform administrator                    # FeatureContext::iAmAPlatformAdministrator()
      WebDriver\Exception\UnknownError: Timed out waiting 45 seconds for Firefox to start.
      Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
      System info: host: 'iruka', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-21-generic', java.version: '1.8.0_151'
      Driver info: driver.version: unknown in /var/www/chamilo111x/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /var/www/chamilo111x/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(13, 'Timed out waiti...')
      #1 /var/www/chamilo111x/vendor/instaclick/php-webdriver/lib/WebDriver/WebDriver.php(70): WebDriver\AbstractWebDriver->curl('POST', '/session', Array, Array)
      #2 /var/www/chamilo111x/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(287): WebDriver\WebDriver->session(Array, Array)
```

The main problem here seems to be `WebDriver\Exception\UnknownError: Timed out waiting 45 seconds for Firefox to start.`, because a Firefox window appears but it doesn't do anything and after 45 seconds, behat reports the error.

I've searched a little and it seems like this is related to the engine change in Firefox 56. Somehow the old connection interface doesn't work anymore.

I found this report on Gecko that might help:
https://stackoverflow.com/a/46857336/6499848
which leads to the releases of Gecko https://github.com/mozilla/geckodriver/releases where version 0.18.0 fixes something related to timeouts with Firefox 56.

I'm not sure what the link is between those, but I also tried to configure Chrome as the browser to test with, with no success (not sure what the browser-name: setting should be in behat.yml)

Any idea on how to fix this?

**Comment by jmontoyaa** [comment]
Can you provide steps how to use Firefox to try behat tests instead of Chrome?

Currently the chromedriver steps found here work for me:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/tests/behat/README.md

**Comment by ywarnier** [comment]
Well, actually I don't do anything special. On my Ubuntu, chrome is available as either google-chrome or google-chrome-stable or chromium-browser, but not as the command "chrome" (which is why, I guess, Firefox gets started instead). Is it available as "chrome" on your computer?

**Comment by jmontoyaa** [comment]
For chrome you need to install the chromedriver.
With the instructions I did in the readme it works for me with Chrome if you want to try with firefox maybe you should install the geckodriver instead the chromedriver and add the parameter "Dwebdriver.gecko.driver"

java -Dwebdriver.gecko.driver="/path/to/geckodriver" -jar vendor/bin/selenium-server-standalone-3.3.1.jar

Check here:

https://github.com/lmc-eu/steward/wiki/Selenium-server-&-browser-drivers

**Comment by AngelFQC** [comment]
Hi!
Now, the behat configuration in chamilo works with chrome 'by default'
If you want to test with Firefox it's a little bit more tricky:
- Download and uncompress the geckodriver from https://github.com/mozilla/geckodriver/releases
- You need change the `behat.yml` file to remove the browser setting (since the default browser on Behat/Mink is Firefox). And enable [Marionette](https://firefox-source-docs.mozilla.org/testing/marionette/marionette/index.html) in the capabilities
```yml
default:
    extensions:
        Behat\MinkExtension:
          base_url: http://localhost
          goutte: ~
          show_cmd: 'open %s'
          selenium2:
              wd_host: "http://127.0.0.1:4444/wd/hub"
              capabilities: {marionette: true}
          default_session: selenium2
          javascript_session: selenium2
          files_path: "%paths.base%/../../web/"

    suites:
        default:
            paths: ["%paths.base%/features"]
    formatters:
        pretty: true
```
- Run selenium server with `java -Dwebdriver.gecko.driver="/PATH/TO/geckodriver" -jar selenium-server-standalone-3.8.1.jar -enablePassThrough false`
