### ISSUE TITLE
[C2] Add tool icon background from design

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5440]
The C2 design created initially adds a "color patch" icon as background for the tool icons in the course.

Use the attached file as background to add to the course home style (should also appear behind the course introduction icon when there is not course introduction). Ideally the element should use the primary color used by the too icons themselves, just more transparent.

The attached SVG has been designed to use the "color" CSS property of the container of the icon:
```css
/* Set the color for the entire icon */
.tool-icon-background {
  color: #ff0000; /* Red */
}
```
(#ff0000 should be replaced by the call to the primary color).

The default size of the icon is 64x64, which should be OK for the tool icons but will probably require some kind of change for the course introduction section icon.
![tool-background](https://github.com/chamilo/chamilo-lms/assets/609839/5a4251fc-680c-42a3-83ae-3a9d35f2b55a)
