### ISSUE TITLE
[C2] Remove config/configuration.php

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5702]
config/configuration.php is a remnant of Chamilo 1.11 and only contains a few settings that are not yet supported with the new C2 (but that should be reintegrated in the future, so we don't want to loose them).

This is what configuration.php currently looks like on a newly-installed Chamilo 2.0 setup (I'm removing documentation for the purpose of synthesis in the code below):
```
$_configuration['db_manager_enabled'] = false;
$_configuration[1]['hosting_limit_users'] = 0;
$_configuration[1]['hosting_limit_teachers'] = 0;
$_configuration[1]['hosting_limit_courses'] = 0;
$_configuration[1]['hosting_limit_sessions'] = 0;
$_configuration[1]['hosting_limit_disk_space'] = 0;
$_configuration[1]['hosting_limit_active_courses'] = 0;
$_configuration['hosting_total_size_limit'] = 0;
$_configuration['security_key'] = 'abcdefabcdef123456';
$_configuration['software_name'] = 'Chamilo';
$_configuration['software_url'] = 'https://chamilo.org/';
$_configuration['deny_delete_users'] = false;
```
The settings without a URL prefix (`[1]` in this example) can safely be moved to .env. Just change them to uppercase:
```
DB_MANAGER_ENABLED='0'
SECURITY_KEY='abcdefabcdef123456'     # not sure this one is still used...
SOFTWARE_NAME='Chamilo'
SOFTWARE_URL='https://chamilo.org/';
DENY_DELETE_USERS='0'
```
(make sure these are converted correctly from any place in the code).

The settings related to hosting limits can be stored in a *new* file called config/hosting_limits.yml.dist, which will be copied to config/hosting_limits.yml manually if anyone needs to define values there:
```
hosting_limits:
    urls:
        1:
            - hosting_limit_users: 0
            - hosting_limit_teachers: 0
            - hosting_limit_courses: 0
            - hosting_limit_sessions: 0
            - hosting_limit_disk_space: 0
            - hosting_limit_active_courses: 0
            - hosting_total_size_limit: 0
        2:
            - hosting_limit_users: 0
            - hosting_limit_teachers: 0
            - hosting_limit_courses: 0
            - hosting_limit_sessions: 0
            - hosting_limit_disk_space: 0
            - hosting_limit_active_courses: 0
            - hosting_total_size_limit: 0
```

This requires a migration (to move the remaining settings from configuration.php to the .env and .yml files, and a review of the code in search for the use of those settings, to replace them.
