### ISSUE TITLE
[C2] Reimplement User and Class synchronisation with Entra AD (Ex Azure AD)

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#6201]
In Chamilo 1.11.x we have a plugin "azure_active_directory" that is used for authentification through Azure AD and synchronisation of users and class.
The authentification part and user creation and update (with field correspondance definition) on login is done directly in Core Chamilo in master in the config/authentification.yaml file.

What we are missing is the configuration for group id that correspond to Admin, session admin, teacher to assign the correct role in Chamilo.
We are also missing the command for user and class syncronisation. We need to be able to do complete sync and also delta sync as in 1.11.x and configure as usergroup Regex filter.

This has to be implemented to reproduce the functionalities that were in the plugin in 1.11.x

**Comment by ywarnier** [comment]
@AngelFQC How are we doing on this one?

**Comment by AngelFQC** [comment]
Done with these commits

4b071274dad01f70d90e84975ab52b5c5e9b57be
1ee5f2566f014230060e9c6cff7c6eb01554dfad
012ec180de75d7f3018388d7ab02c0763bb176c7
f35579c02121bc723add13a0890f5e072914048d
552ce2969a8848a8ee3074e59993e55f87ddea91
97d0a0a5918a859338517475e1f1fa5efde9fc7e

**Comment by NicoDucou** [comment]
To use it, we set the configuration of the azure bloc in config/authentication.yaml
```
azure:
                    enabled: true
                    title: 'Azure'
                    client_id: 'XXXXXXXXXXX'
                    client_secret: 'XXXXXXXXXXXXX'
                    url_api: 'https://graph.microsoft.com'
                    tenant: 'XXXXXXXXXXXXXXX'
                    force_logout: false
                    provisioning: true
                    update_users: true
                    group_id:
                        admin: ''
                        session_admin: 'XXXXXXXXXXX'
                        teacher: ''
                    existing_user_verification_order: ''
                    deactivate_nonexisting_users: false
                    script_users_delta: true
                    script_usergroups_delta: true
                    group_filter_regex: ''

```
The XXXXXXXXXX are information from the azure Portail in the Entra ID interface.


Then in the Chamilo root folder we execute the commands :
- php bin/console app:azure-sync-users
- php bin/console app:azure-sync-usergroups


It is important to set firstname, lastname, and email in the entra ID User configuration to avoid error in the synchronisation.
